org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000
systemProp.org.gradle.internal.repository.max.retries=8
systemProp.https.protocols=TLSv1.2
systemProp.jdk.tls.client.protocols=TLSv1.2
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
android.builtInKotlin=false
android.newDsl=false
